version: '3.7'

services:
 mssql-docker-enhanced:
    image: usildevops/mssql-docker-enhanced
    container_name: mssql-docker-enhanced
    shm_size: 1g
    ports:
     - "1433:1433"
    environment:
      ACCEPT_EULA: 1
      MSSQL_PID: Developer
      MSSQL_USER: sa
      MSSQL_SA_PASSWORD: 70quasWNl*o#nu4U
      TZ: America/Lima
    volumes:
      - ./data:/var/opt/mssql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


      